### ISSUE TITLE
Fix new app target folder

### ISSUE THREAD

**Issue by alekseiismirnov** [alekseiismirnov/quotes#7]
`Dockerfile`:
```
&& rails new quotes /app/quotes --api -d postgresql -T -s --skip-git 
```

log:
```
etching rails 7.0.8
Installing rails 7.0.8
Bundle complete! 6 Gemfile dependencies, 56 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
/bin/sh: /app/quotes/bin/bundle: not found
```

**Comment by alekseiismirnov** [comment]
```
WARNING:  You don't have /home/lesha/.local/share/gem/ruby/3.0.0/bin in your PATH,
	  gem executables will not run.
```

```
web] | Successfully installed rails-7.0.3.1
[web] | 36 gems installed
[web] |        exist  
[web] |         skip  README.md
/home/lesha/.local/share/gem/ruby/3.0.0/gems/thor-1.3.0/lib/thor/actions/create_file.rb:64:in `initialize': Permission denied @ rb_sysopen - /app/quotes/Rakefile (Errno::EACCES)
	from /home/lesha/.local/share/gem/ruby/3.0.0/gems/thor-1.3.0/lib/thor/actions/create_file.rb:64:in `open'
```

**Comment by alekseiismirnov** [comment]
Find why is locally installed gems are inaccessible as in the comment above. 
And recall, why all ruby gems installation was moved to the entry point script from the Dockerfile.

**Comment by alekseiismirnov** [comment]
[web] | PATH: /usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin
[web] | *****
Failed to load /home/lesha/.gemrc because it doesn't contain valid YAML hash
WARNING:  You don't have /home/lesha/.local/share/gem/ruby/3.0.0/bin in your PATH,
	  gem executables will not run.

**Comment by alekseiismirnov** [comment]
web volume mounts ro
```
    volumes:
      - type: bind
        source: .
        target: /app/quotes
        driver_opts:
          o: z
        bind:
          userns: keep-id
```
where would to put ':z' and `--userns=keep-id ` ?

https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference

**Comment by alekseiismirnov** [comment]
https://www.redhat.com/sysadmin/container-video-series

again 
```
/home/lesha/.local/share/gem/ruby/3.0.0/gems/thor-1.3.0/lib/thor/actions/create_file.rb:64:in `initialize': Permission denied @ rb_sysopen - /app/quotes/Rakefile (Errno::EACCES)
	from /home/lesha/.local/share/gem/ruby/3.0.0/gems/thor-1.3.0/lib/thor/actions/create_file.rb:64:in `open'
	from /home/lesha/.local/share/gem/ruby/3.0.0/gems/thor-1.3.0/lib/thor/actions/create_file.rb:64:in `block in invoke!'
```

**Comment by alekseiismirnov** [comment]
```
[web] | /app/quotes
[web] | total 16K    
[web] | -rw-r--r--    1 root     root        1.1K Jan  8 12:41 Dockerfile
[web] | -rw-r--r--    1 root     root         322 Jan  4 09:32 README.md
[web] | -rw-r--r--    1 root     root           0 Jan  9 17:33 me
[web] | -rw-r--r--    1 root     root         692 Jan  9 17:29 podman-compose.yml
[web] | -rw-r--r--    1 root     root        1.1K Jan 12 16:16 run_rails.sh
```

**Comment by alekseiismirnov** [comment]
Ownership changes correctly, but directory mounts in container as root owned:
```
dr-xr-xr-x    1 root     root            17 Jan 18 09:59 .
dr-xr-xr-x    1 root     root            17 Jan 18 09:59 ..
drwxr-xr-x    2 lesha    lesha           22 Jan 18 09:58 app
drwxr-xr-x    1 root     root          4096 Apr  1  2021 bin
```
switch "mount point"

```
drwxr-xr-x    1 root     root            19 Jan 18 09:58 .
dr-xr-xr-x    1 root     root            17 Jan 18 09:59 ..
drwxr-xr-x    3 root     root           112 Jan 18 09:58 lesha
```

**Comment by alekseiismirnov** [comment]
Done
caused mostly by the error in `podman-compose.yml'
```
  web:

    userns_mode: keep-id
```
